---
- name: Get existing VMs
  block:
    - name: Include get vms task
      ansible.builtin.include_tasks: vms/get.yml
      vars:
        app_tag: gateway
        private_host_groups:
          - aap
          - gateway_private
        public_host_groups:
          - gateway_public
      tags:
        - gateway

    - name: Add public IP host to installer
      when: |
        (infrastructure_existing_vm is defined
        and infrastructure_existing_vm.instances | length > 0)
        and (groups.installer is not defined
        or groups.installer | length == 0)
      ansible.builtin.add_host:
        groups:
          - installer
        name: "{{ infrastructure_existing_vm.instances[0].public_ip_address }}"
      tags:
        - gateway

- name: Set number of Gateway VMs to create
  ansible.builtin.set_fact:
    infrastructure_gateway_vms_to_create: "{{ infrastructure_gateway_instances - (infrastructure_existing_vm.instances | default([]) | length) }}"
  tags:
    - gateway

- name: Output number of VMs to create
  ansible.builtin.debug:
    msg: "Creating Gateway VMs: {{ infrastructure_gateway_vms_to_create }}"
  tags:
    - gateway

- name: Create VMs
  when: infrastructure_gateway_vms_to_create | int > 0
  ignore_errors: true
  vars:
    subnet_index: "{{ lookup('ansible.utils.index_of', infrastructure_vpc_subnets, 'eq', 'gateway', 'name') }}"
  block:
    - name: Include create vm task
      ansible.builtin.include_tasks: vms/create.yml
      loop: "{{ query('sequence', 'start=1 end=' + (infrastructure_gateway_vms_to_create | string)) }}"
      vars:
        instance_type: "{{ infrastructure_gateway_shape }}"
        ami: "{{ infrastructure_gateway_ami }}"
        vm_name_prefix: gateway-
        subnet: "{{ infrastructure_subnet_ids[subnet_index | int] }}"
        private_host_groups:
          - aap
          - gateway_private
        public_host_groups:
          - gateway_public
        app_tag: gateway
      tags:
        - gateway

    - name: Wait 10 mins for VMs to become available
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 600
      loop: "{{ groups.public }}"
      