---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  tags:
    - controller
    - hub
    - eda
    - "{{ 'gateway' if (infrastructure_aap_version is version('2.5', '>=')) else omit }}"

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - python3-psycopg2
      - ansible-automation-platform-installer
    state: latest
  tags:
    - controller
    - hub
    - eda
    - "{{ 'gateway' if (infrastructure_aap_version is version('2.5', '>=')) else omit }}"
